import type { DemoRoadmap, Idea } from './demoData'

// Generates a clean, formatted roadmap file and triggers a browser download.
// No sign-in required — users grab exactly the roadmap they want.
export function downloadRoadmap(idea: Pick<Idea, 'title' | 'tagline'>, roadmap: DemoRoadmap) {
  const lines: string[] = []
  lines.push(`# ${idea.title} — ${roadmap.name}`)
  lines.push('')
  if (idea.tagline) lines.push(`> ${idea.tagline}`)
  lines.push('')
  lines.push(`- Timeline: ${roadmap.duration_days} days`)
  lines.push(`- Estimated cost: ${roadmap.cost_estimate}`)
  lines.push(`- Difficulty: ${'●'.repeat(roadmap.difficulty)}${'○'.repeat(5 - roadmap.difficulty)} (${roadmap.difficulty}/5)`)
  lines.push('')
  lines.push('## Steps')
  lines.push('')
  for (const s of roadmap.steps) {
    lines.push(`### ${s.order}. ${s.title}`)
    lines.push(s.description)
    if (s.deliverable) lines.push(`Deliverable: ${s.deliverable}`)
    lines.push('')
  }
  lines.push('---')
  lines.push('Generated by Hidden Ideas — explore more at your library.')

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${idea.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${roadmap.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
