import type { DemoRoadmap, Idea } from './demoData'

// Brand palette (RGB)
const INK: [number, number, number] = [20, 20, 20]
const YELLOW: [number, number, number] = [255, 225, 17]
const GREEN: [number, number, number] = [47, 180, 87]
const MUTED: [number, number, number] = [90, 90, 90]

// Generates a clean, on-brand PDF roadmap and triggers a browser download.
// No sign-in required — users grab exactly the roadmap they want, as a real PDF.
export async function downloadRoadmap(idea: Pick<Idea, 'title' | 'tagline'>, roadmap: DemoRoadmap) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48 // margin
  const CW = W - M * 2 // content width

  // ---- Header band (yellow with ink title) ----
  const headerH = 150
  doc.setFillColor(...YELLOW)
  doc.rect(0, 0, W, headerH, 'F')
  doc.setFillColor(...INK)
  doc.rect(0, headerH, W, 4, 'F') // ink underline

  // biz wordmark
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(30)
  doc.text('biz', M, 52)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('BUSINESS IDEAS HIDING IN PLAIN SIGHT', M + 46, 51)

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  const titleLines = doc.splitTextToSize(idea.title, CW)
  doc.text(titleLines, M, 90)
  let hy = 90 + titleLines.length * 22
  if (idea.tagline) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(40, 40, 40)
    const tl = doc.splitTextToSize(idea.tagline, CW)
    doc.text(tl, M, hy)
  }

  // ---- Meta strip ----
  let y = headerH + 36
  const chips = [
    `Roadmap: ${roadmap.name}`,
    `Timeline: ${roadmap.duration_days} days`,
    `Cost: ${roadmap.cost_estimate}`,
    `Difficulty: ${roadmap.difficulty}/5`,
  ]
  doc.setFontSize(9.5)
  let cx = M
  for (const c of chips) {
    doc.setFont('helvetica', 'bold')
    const tw = doc.getTextWidth(c)
    const pad = 9
    const cw = tw + pad * 2
    if (cx + cw > W - M) { cx = M; y += 30 }
    doc.setDrawColor(...INK)
    doc.setLineWidth(1.2)
    doc.setFillColor(255, 255, 255)
    doc.roundedRect(cx, y - 12, cw, 22, 11, 11, 'FD')
    doc.setTextColor(...INK)
    doc.text(c, cx + pad, y + 3)
    cx += cw + 8
  }

  // ---- Steps heading ----
  y += 44
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...INK)
  doc.text('Your step-by-step roadmap', M, y)
  y += 10
  doc.setDrawColor(...INK)
  doc.setLineWidth(2)
  doc.line(M, y, M + 90, y)
  y += 26

  // ---- Steps ----
  const bottom = H - 60
  for (const s of roadmap.steps) {
    // measure block height
    doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5)
    const tLines = doc.splitTextToSize(`${s.order}.  ${s.title}`, CW - 24)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
    const dLines = doc.splitTextToSize(s.description, CW - 24)
    const dLine = s.deliverable ? doc.splitTextToSize(`Deliverable: ${s.deliverable}`, CW - 24) : []
    const blockH = 8 + tLines.length * 15 + dLines.length * 13 + (dLine.length ? 6 + dLine.length * 12 : 0) + 16

    if (y + blockH > bottom) { doc.addPage(); y = 60 }

    // step accent dot
    doc.setFillColor(...GREEN)
    doc.circle(M + 4, y - 2, 4, 'F')

    doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5); doc.setTextColor(...INK)
    doc.text(tLines, M + 16, y)
    y += tLines.length * 15 + 2

    doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...MUTED)
    doc.text(dLines, M + 16, y)
    y += dLines.length * 13

    if (dLine.length) {
      y += 4
      doc.setTextColor(...GREEN)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(9.5)
      doc.text(dLine, M + 16, y + 6)
      y += dLine.length * 12 + 4
    }
    y += 14
  }

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setDrawColor(220, 220, 220); doc.setLineWidth(1)
    doc.line(M, H - 40, W - M, H - 40)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...MUTED)
    doc.text('Generated by biz — a living library of hidden business ideas.', M, H - 26)
    doc.text(`Page ${p} of ${pageCount}`, W - M, H - 26, { align: 'right' })
  }

  const fname = `${idea.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${roadmap.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`
  doc.save(fname)
}

// ---- Built-roadmap (phased) PDF export for the /builder tool ----
import type { BuiltRoadmap } from './roadmapBuilder'
import { formatINR, totalCost, totalDays, progress } from './roadmapBuilder'

export async function downloadBuiltRoadmap(r: BuiltRoadmap) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48
  const CW = W - M * 2

  // Header band
  const headerH = 150
  doc.setFillColor(...YELLOW); doc.rect(0, 0, W, headerH, 'F')
  doc.setFillColor(...INK); doc.rect(0, headerH, W, 4, 'F')
  doc.setTextColor(...INK); doc.setFont('helvetica', 'bold'); doc.setFontSize(30)
  doc.text('biz', M, 52)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
  doc.text('YOUR CUSTOM ROADMAP', M + 46, 51)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20)
  const titleLines = doc.splitTextToSize(r.title, CW)
  doc.text(titleLines, M, 90)
  let hy = 90 + titleLines.length * 22
  if (r.goal) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(40, 40, 40)
    doc.text(doc.splitTextToSize(r.goal, CW), M, hy)
  }

  // Meta strip
  const prog = progress(r)
  let y = headerH + 36
  const chips = [
    `Category: ${r.category}`,
    `Timeline: ~${totalDays(r)} days`,
    `Budget: ${formatINR(totalCost(r))}`,
    `Progress: ${prog.done}/${prog.total} (${prog.pct}%)`,
  ]
  doc.setFontSize(9.5); let cx = M
  for (const c of chips) {
    doc.setFont('helvetica', 'bold')
    const cw = doc.getTextWidth(c) + 18
    if (cx + cw > W - M) { cx = M; y += 30 }
    doc.setDrawColor(...INK); doc.setLineWidth(1.2); doc.setFillColor(255, 255, 255)
    doc.roundedRect(cx, y - 12, cw, 22, 11, 11, 'FD')
    doc.setTextColor(...INK); doc.text(c, cx + 9, y + 3)
    cx += cw + 8
  }
  y += 44

  const bottom = H - 60
  let stepNo = 0
  r.phases.forEach((phase, pi) => {
    // phase header
    if (y + 40 > bottom) { doc.addPage(); y = 60 }
    doc.setFillColor(...INK)
    doc.roundedRect(M, y - 14, CW, 26, 6, 6, 'F')
    doc.setTextColor(...YELLOW); doc.setFont('helvetica', 'bold'); doc.setFontSize(12)
    doc.text(`PHASE ${pi + 1} — ${phase.name.toUpperCase()}`, M + 10, y + 3)
    y += 30
    doc.setTextColor(...MUTED); doc.setFont('helvetica', 'normal'); doc.setFontSize(9.5)
    doc.text(doc.splitTextToSize(phase.summary, CW), M, y)
    y += 20

    for (const s of phase.steps) {
      stepNo++
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5)
      const tLines = doc.splitTextToSize(`${stepNo}.  ${s.title}`, CW - 24)
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
      const dLines = doc.splitTextToSize(s.description, CW - 24)
      const meta = `~${s.days} day${s.days > 1 ? 's' : ''}  ·  ${formatINR(s.cost)}${s.deliverable ? '  ·  Deliverable: ' + s.deliverable : ''}`
      const mLines = doc.splitTextToSize(meta, CW - 24)
      const blockH = tLines.length * 15 + dLines.length * 13 + mLines.length * 12 + 22
      if (y + blockH > bottom) { doc.addPage(); y = 60 }

      doc.setFillColor(...GREEN); doc.circle(M + 4, y - 2, 4, 'F')
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5); doc.setTextColor(...INK)
      doc.text(tLines, M + 16, y); y += tLines.length * 15 + 2
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...MUTED)
      doc.text(dLines, M + 16, y); y += dLines.length * 13 + 2
      doc.setTextColor(...GREEN); doc.setFont('helvetica', 'bold'); doc.setFontSize(9)
      doc.text(mLines, M + 16, y); y += mLines.length * 12 + 12
    }
    y += 8
  })

  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setDrawColor(220, 220, 220); doc.setLineWidth(1)
    doc.line(M, H - 40, W - M, H - 40)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...MUTED)
    doc.text('Built with biz — the roadmap builder for hidden business ideas.', M, H - 26)
    doc.text(`Page ${p} of ${pageCount}`, W - M, H - 26, { align: 'right' })
  }

  doc.save(`${r.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-roadmap.pdf`)
}

// ---- AI (Gemini) 7-section roadmap PDF export ----
import type { AIRoadmap } from './roadmapAI'

export async function downloadAIRoadmap(r: AIRoadmap) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48
  const CW = W - M * 2
  const bottom = H - 60
  let y = 0

  const ensure = (need: number) => { if (y + need > bottom) { doc.addPage(); y = 60 } }
  const para = (text: string, size = 10, color: [number, number, number] = MUTED, indent = 0) => {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(size); doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, CW - indent)
    ensure(lines.length * (size + 3))
    doc.text(lines, M + indent, y)
    y += lines.length * (size + 3)
  }

  // Header band
  const headerH = 150
  doc.setFillColor(...YELLOW); doc.rect(0, 0, W, headerH, 'F')
  doc.setFillColor(...INK); doc.rect(0, headerH, W, 4, 'F')
  doc.setTextColor(...INK); doc.setFont('helvetica', 'bold'); doc.setFontSize(30)
  doc.text('biz', M, 52)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
  doc.text('AI BUSINESS ROADMAP', M + 46, 51)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(19)
  const titleLines = doc.splitTextToSize(r.title, CW)
  doc.text(titleLines, M, 88)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10.5); doc.setTextColor(40, 40, 40)
  const sumLines = doc.splitTextToSize(r.summary, CW).slice(0, 2)
  doc.text(sumLines, M, 88 + titleLines.length * 21)

  // Meta strip
  y = headerH + 34
  const chips = [`Difficulty: ${r.difficulty}`, `Timeline: ${r.totalTimeline}`, `Est. cost: ${r.estimatedCost}`]
  if (r.niche) chips.push(`Niche: ${r.niche}`)
  doc.setFontSize(9.5); let cx = M
  for (const c of chips) {
    doc.setFont('helvetica', 'bold')
    const cw = doc.getTextWidth(c) + 18
    if (cx + cw > W - M) { cx = M; y += 30 }
    doc.setDrawColor(...INK); doc.setLineWidth(1.2); doc.setFillColor(255, 255, 255)
    doc.roundedRect(cx, y - 12, cw, 22, 11, 11, 'FD')
    doc.setTextColor(...INK); doc.text(c, cx + 9, y + 3)
    cx += cw + 8
  }
  y += 42

  const heading = (n: number, t: string) => {
    ensure(48)
    doc.setFillColor(...INK); doc.roundedRect(M, y - 15, CW, 28, 6, 6, 'F')
    doc.setTextColor(...YELLOW); doc.setFont('helvetica', 'bold'); doc.setFontSize(12.5)
    doc.text(`${n}.  ${t.toUpperCase()}`, M + 10, y + 3)
    y += 32
  }
  const bullet = (text: string, label?: string) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
    const full = label ? `${label}: ${text}` : text
    const lines = doc.splitTextToSize(full, CW - 18)
    ensure(lines.length * 13 + 4)
    doc.setFillColor(...GREEN); doc.circle(M + 4, y - 3, 3, 'F')
    doc.setTextColor(...INK); doc.text(lines, M + 14, y)
    y += lines.length * 13 + 4
  }

  // 1. Registration
  heading(1, 'Registration process')
  r.registration.forEach((s, i) => { bullet(s.detail, `${i + 1}. ${s.step}`) })
  y += 8

  // 2. Licenses
  heading(2, 'Licenses & permissions')
  r.licenses.forEach((l) => {
    bullet(`${l.authority}${l.cost ? ' · ' + l.cost : ''}${l.mandatory ? ' · Mandatory' : ' · Optional'}`, l.name)
    if (l.notes) para(l.notes, 9, MUTED, 14)
  })
  y += 8

  // 3. Fees
  heading(3, 'Charges & fees')
  r.fees.forEach((f) => { bullet(`${f.amount}${f.frequency ? ' (' + f.frequency + ')' : ''}`, f.item) })
  y += 8

  // 4. Suppliers
  heading(4, 'Suppliers & manufacturers')
  r.suppliers.forEach((s) => {
    bullet(`${s.priceRange ?? ''}${s.whatToLookFor ? (s.priceRange ? ' — ' : '') + s.whatToLookFor : ''}`, s.category)
    para(`IndiaMART search: "${s.indiamartQuery}"`, 9, GREEN, 14)
  })
  y += 8

  // 5. Market & competitors
  heading(5, 'Market insights & competitors')
  para(r.market.overview, 10, INK)
  if (r.market.trends.length) para('Trends: ' + r.market.trends.join(' · '), 9, MUTED)
  y += 4
  r.market.competitors.forEach((c) => { bullet(c.positioning, c.name) })
  y += 8

  // 6. Timeline
  heading(6, 'Estimated timeline')
  r.timeline.forEach((t) => {
    bullet('', `${t.phase} — ${t.duration}`)
    t.milestones.forEach((m) => para('• ' + m, 9.5, MUTED, 16))
  })
  y += 8

  // 7. Challenges
  heading(7, 'Common challenges & solutions')
  r.challenges.forEach((c) => {
    bullet(c.challenge)
    para('Fix: ' + c.solution, 9.5, GREEN, 14)
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setDrawColor(220, 220, 220); doc.setLineWidth(1)
    doc.line(M, H - 40, W - M, H - 40)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...MUTED)
    doc.text('Built with biz — AI business roadmaps. Verify licenses & fees with official sources.', M, H - 26)
    doc.text(`Page ${p} of ${pageCount}`, W - M, H - 26, { align: 'right' })
  }

  doc.save(`${r.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}-roadmap.pdf`)
}
