import type { DemoRoadmap, Idea } from './demoData'

// Brand palette (RGB)
const INK: [number, number, number] = [20, 20, 20]
const YELLOW: [number, number, number] = [255, 225, 17]
const GREEN: [number, number, number] = [47, 180, 87]
const MUTED: [number, number, number] = [90, 90, 90]

// Generates a clean, on-brand PDF roadmap and triggers a browser download.
// No sign-in required — users grab exactly the roadmap they want, as a real PDF.
export async function downloadRoadmap(idea: Pick<Idea, 'title' | 'tagline'>, roadmap: DemoRoadmap) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48 // margin
  const CW = W - M * 2 // content width

  // ---- Header band (yellow with ink title) ----
  const headerH = 150
  doc.setFillColor(...YELLOW)
  doc.rect(0, 0, W, headerH, 'F')
  doc.setFillColor(...INK)
  doc.rect(0, headerH, W, 4, 'F') // ink underline

  // biz wordmark
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(30)
  doc.text('biz', M, 52)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('BUSINESS IDEAS HIDING IN PLAIN SIGHT', M + 46, 51)

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  const titleLines = doc.splitTextToSize(idea.title, CW)
  doc.text(titleLines, M, 90)
  let hy = 90 + titleLines.length * 22
  if (idea.tagline) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(40, 40, 40)
    const tl = doc.splitTextToSize(idea.tagline, CW)
    doc.text(tl, M, hy)
  }

  // ---- Meta strip ----
  let y = headerH + 36
  const chips = [
    `Roadmap: ${roadmap.name}`,
    `Timeline: ${roadmap.duration_days} days`,
    `Cost: ${roadmap.cost_estimate}`,
    `Difficulty: ${roadmap.difficulty}/5`,
  ]
  doc.setFontSize(9.5)
  let cx = M
  for (const c of chips) {
    doc.setFont('helvetica', 'bold')
    const tw = doc.getTextWidth(c)
    const pad = 9
    const cw = tw + pad * 2
    if (cx + cw > W - M) { cx = M; y += 30 }
    doc.setDrawColor(...INK)
    doc.setLineWidth(1.2)
    doc.setFillColor(255, 255, 255)
    doc.roundedRect(cx, y - 12, cw, 22, 11, 11, 'FD')
    doc.setTextColor(...INK)
    doc.text(c, cx + pad, y + 3)
    cx += cw + 8
  }

  // ---- Steps heading ----
  y += 44
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...INK)
  doc.text('Your step-by-step roadmap', M, y)
  y += 10
  doc.setDrawColor(...INK)
  doc.setLineWidth(2)
  doc.line(M, y, M + 90, y)
  y += 26

  // ---- Steps ----
  const bottom = H - 60
  for (const s of roadmap.steps) {
    // measure block height
    doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5)
    const tLines = doc.splitTextToSize(`${s.order}.  ${s.title}`, CW - 24)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
    const dLines = doc.splitTextToSize(s.description, CW - 24)
    const dLine = s.deliverable ? doc.splitTextToSize(`Deliverable: ${s.deliverable}`, CW - 24) : []
    const blockH = 8 + tLines.length * 15 + dLines.length * 13 + (dLine.length ? 6 + dLine.length * 12 : 0) + 16

    if (y + blockH > bottom) { doc.addPage(); y = 60 }

    // step accent dot
    doc.setFillColor(...GREEN)
    doc.circle(M + 4, y - 2, 4, 'F')

    doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5); doc.setTextColor(...INK)
    doc.text(tLines, M + 16, y)
    y += tLines.length * 15 + 2

    doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...MUTED)
    doc.text(dLines, M + 16, y)
    y += dLines.length * 13

    if (dLine.length) {
      y += 4
      doc.setTextColor(...GREEN)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(9.5)
      doc.text(dLine, M + 16, y + 6)
      y += dLine.length * 12 + 4
    }
    y += 14
  }

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setDrawColor(220, 220, 220); doc.setLineWidth(1)
    doc.line(M, H - 40, W - M, H - 40)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...MUTED)
    doc.text('Generated by biz — a living library of hidden business ideas.', M, H - 26)
    doc.text(`Page ${p} of ${pageCount}`, W - M, H - 26, { align: 'right' })
  }

  const fname = `${idea.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${roadmap.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`
  doc.save(fname)
}

// ---- Built-roadmap (phased) PDF export for the /builder tool ----
import type { BuiltRoadmap } from './roadmapBuilder'
import { formatINR, totalCost, totalDays, progress } from './roadmapBuilder'

export async function downloadBuiltRoadmap(r: BuiltRoadmap) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48
  const CW = W - M * 2

  // Header band
  const headerH = 150
  doc.setFillColor(...YELLOW); doc.rect(0, 0, W, headerH, 'F')
  doc.setFillColor(...INK); doc.rect(0, headerH, W, 4, 'F')
  doc.setTextColor(...INK); doc.setFont('helvetica', 'bold'); doc.setFontSize(30)
  doc.text('biz', M, 52)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
  doc.text('YOUR CUSTOM ROADMAP', M + 46, 51)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20)
  const titleLines = doc.splitTextToSize(r.title, CW)
  doc.text(titleLines, M, 90)
  let hy = 90 + titleLines.length * 22
  if (r.goal) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11); doc.setTextColor(40, 40, 40)
    doc.text(doc.splitTextToSize(r.goal, CW), M, hy)
  }

  // Meta strip
  const prog = progress(r)
  let y = headerH + 36
  const chips = [
    `Category: ${r.category}`,
    `Timeline: ~${totalDays(r)} days`,
    `Budget: ${formatINR(totalCost(r))}`,
    `Progress: ${prog.done}/${prog.total} (${prog.pct}%)`,
  ]
  doc.setFontSize(9.5); let cx = M
  for (const c of chips) {
    doc.setFont('helvetica', 'bold')
    const cw = doc.getTextWidth(c) + 18
    if (cx + cw > W - M) { cx = M; y += 30 }
    doc.setDrawColor(...INK); doc.setLineWidth(1.2); doc.setFillColor(255, 255, 255)
    doc.roundedRect(cx, y - 12, cw, 22, 11, 11, 'FD')
    doc.setTextColor(...INK); doc.text(c, cx + 9, y + 3)
    cx += cw + 8
  }
  y += 44

  const bottom = H - 60
  let stepNo = 0
  r.phases.forEach((phase, pi) => {
    // phase header
    if (y + 40 > bottom) { doc.addPage(); y = 60 }
    doc.setFillColor(...INK)
    doc.roundedRect(M, y - 14, CW, 26, 6, 6, 'F')
    doc.setTextColor(...YELLOW); doc.setFont('helvetica', 'bold'); doc.setFontSize(12)
    doc.text(`PHASE ${pi + 1} — ${phase.name.toUpperCase()}`, M + 10, y + 3)
    y += 30
    doc.setTextColor(...MUTED); doc.setFont('helvetica', 'normal'); doc.setFontSize(9.5)
    doc.text(doc.splitTextToSize(phase.summary, CW), M, y)
    y += 20

    for (const s of phase.steps) {
      stepNo++
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5)
      const tLines = doc.splitTextToSize(`${stepNo}.  ${s.title}`, CW - 24)
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
      const dLines = doc.splitTextToSize(s.description, CW - 24)
      const meta = `~${s.days} day${s.days > 1 ? 's' : ''}  ·  ${formatINR(s.cost)}${s.deliverable ? '  ·  Deliverable: ' + s.deliverable : ''}`
      const mLines = doc.splitTextToSize(meta, CW - 24)
      const blockH = tLines.length * 15 + dLines.length * 13 + mLines.length * 12 + 22
      if (y + blockH > bottom) { doc.addPage(); y = 60 }

      doc.setFillColor(...GREEN); doc.circle(M + 4, y - 2, 4, 'F')
      doc.setFont('helvetica', 'bold'); doc.setFontSize(11.5); doc.setTextColor(...INK)
      doc.text(tLines, M + 16, y); y += tLines.length * 15 + 2
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...MUTED)
      doc.text(dLines, M + 16, y); y += dLines.length * 13 + 2
      doc.setTextColor(...GREEN); doc.setFont('helvetica', 'bold'); doc.setFontSize(9)
      doc.text(mLines, M + 16, y); y += mLines.length * 12 + 12
    }
    y += 8
  })

  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setDrawColor(220, 220, 220); doc.setLineWidth(1)
    doc.line(M, H - 40, W - M, H - 40)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...MUTED)
    doc.text('Built with biz — the roadmap builder for hidden business ideas.', M, H - 26)
    doc.text(`Page ${p} of ${pageCount}`, W - M, H - 26, { align: 'right' })
  }

  doc.save(`${r.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-roadmap.pdf`)
}
